DevOps/force-app/main/default/objects/Case/fields/Case_Owner_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_Full_Name__c</fullName>
    <formula>if(or(isblank(Owner:Queue.QueueName), isnull(Owner:Queue.QueueName)), Owner:User.FirstName &amp; &apos; &apos; &amp; Owner:User.LastName, Owner:Queue.QueueName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Owner Full Name</label>
    <type>Text</type>
</CustomField>

DevOps/force-app/main/default/objects/Case/fields/Date_of_Enquiry_or_Referral__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Enquiry_or_Referral__c</fullName>
    <inlineHelpText>Please select Date the Enquiry or Referral was received. This is the date &apos;when&apos; the enquiry or referral was made</inlineHelpText>
    <label>Enquiry/Referral Date</label>
    <type>Date</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/Case_Review__c.object-meta.xml
<CustomObject>
    <description>Use this object to record case reviews</description>
    <label>Case Review</label>
    <nameField>
        <displayFormat>CR-{0000000}</displayFormat>
        <label>Case Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Reviews</relationshipLabel>
    <relationshipName>Case_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Case_Plan_Goals__c.field-meta.xml
<CustomField>
    <fullName>Case_Plan_Goals__c</fullName>
    <label>Case Plan Goals</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Contact_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Contact_Frequency__c</fullName>
    <label>Contact Frequency</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/CSAT_Survey_Completed_If_Closing__c.field-meta.xml
<CustomField>
    <fullName>CSAT_Survey_Completed_If_Closing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CSAT Survey Completed (If Closing)</label>
    <type>Checkbox</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Current_Situation__c.field-meta.xml
<CustomField>
    <fullName>Current_Situation__c</fullName>
    <label>Current Situation</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Date_Of_Review__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Review__c</fullName>
    <label>Date of Review</label>
    <type>Date</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/General_Comments_Notes__c.field-meta.xml
<CustomField>
    <fullName>General_Comments_Notes__c</fullName>
    <label>General Comments/Notes</label>
    <length>31000</length>
    <type>Html</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Initial_Outcome_Star_Completed__c.field-meta.xml
<CustomField>
    <fullName>Initial_Outcome_Star_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initial Outcome Star Completed</label>
    <type>Checkbox</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Multidisciplinary_Review__c.field-meta.xml
<CustomField>
    <fullName>Multidisciplinary_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multidisciplinary Review</label>
    <type>Checkbox</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Number_of_Outcomes_Star_Completed__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Outcomes_Star_Completed__c</fullName>
    <label>Number of Outcomes Star Completed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Program_Worker__c.field-meta.xml
<CustomField>
    <fullName>Program_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Worker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Reviews1</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Risks__c.field-meta.xml
<CustomField>
    <fullName>Risks__c</fullName>
    <label>Risks</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Specialist_Reviewer_1__c.field-meta.xml
<CustomField>
    <fullName>Specialist_Reviewer_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specialist Reviewer 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Reviews2</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Specialist_Reviewer_2__c.field-meta.xml
<CustomField>
    <fullName>Specialist_Reviewer_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specialist Reviewer 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Reviews3</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Specialist_Reviewer_3__c.field-meta.xml
<CustomField>
    <fullName>Specialist_Reviewer_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specialist Reviewer 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Reviews4</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOps/force-app/main/default/objects/Case_Review__c/fields/Specialist_Reviewer_4__c.field-meta.xml
<CustomField>
    <fullName>Specialist_Reviewer_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specialist Reviewer 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Reviews5</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOps/force-app/main/default/classes/CaseReviewPDF.cls
public class CaseReviewPDF {
    
    public Case c {get;set;}
    public List<Case_Review__c> caseReviews {get; set;}

    public String exportTime {get;set;}
    public String dateOfReferralTime {get;set;}
    public String dateClosedTime {get;set;}
    
    public CaseReviewPDF(ApexPages.StandardController controller) {
        
        String caseId = apexpages.currentpage().getparameters().get('id');

        //query the case for specific fields
        c = [SELECT id, Contact.FullName__c,  Contact.Contact_Number__c, CaseNumber, OwnerId, Case_Owner_Full_Name__c, Program_Name__c, Date_of_Enquiry_or_Referral__c, ClosedDate FROM Case WHERE id = :caseId];
        
        //query all of this case's case reviews ordered by its creation date
        caseReviews = [SELECT id, Case_Plan_Goals__c, Name, Contact_Frequency__c, CSAT_Survey_Completed_If_Closing__c, Current_Situation__c, Date_Of_Review__c, General_Comments_Notes__c, Initial_Outcome_Star_Completed__c, Reviewer__r.FullName__c, Multidisciplinary_Review__c, Number_of_Outcomes_Star_Completed__c, Program_Worker__r.FullName__c, Risks__c, Specialist_Reviewer_1__r.FullName__c, Specialist_Reviewer_2__r.FullName__c, Specialist_Reviewer_3__r.FullName__c, Specialist_Reviewer_4__r.FullName__c FROM Case_Review__c WHERE Case__c = :caseId];        
        exportTime = GmtToAest(System.Now());
        
        //dateOfReferralTime = GmtToAest(c.Date_of_Enquiry_or_Referral__c);
        //dateClosedTime = GmtToAest(c.ClosedDate);
    }
    
    public String GmtToAest(DateTime dt) {
        String strConvertedDate = dt.format('MM/dd/yyyy HH:mm:ss', 'Australia/Sydney');
        return strConvertedDate;
    }
    
}