DevOps/force-app/main/default/objects/Case/fields/CIMS_Cluster_Id__c.field-meta.xml
<CustomField>
    <fullName>CIMS_Cluster_Id__c</fullName>
    <label>CIMS Cluster Id</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

DevOps/force-app/main/default/objects/Case/fields/CIMS_Unique_Check__c.field-meta.xml
<CustomField>
    <fullName>CIMS_Unique_Check__c</fullName>
    <externalId>true</externalId>
    <label>CIMS Unique Check</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

DevOps/force-app/main/default/objects/Case/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Social Futures Program for which an enquiry is being made, or the Program that has received the Referral and will take on the Case.</description>
    <inlineHelpText>The Social Futures Program for which an enquiry is being made, or the Program that has received the Referral and will take on the Case.</inlineHelpText>
    <label>Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program__c.Program_Type__c</field>
            <operation>notEqual</operation>
            <value>Headspace, NDIS, Standby Response Service</value>
        </filterItems>
        <filterItems>
            <field>Program__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOps/force-app/main/default/objects/Outbound_Referral__c/Outbound_Referral__c.object-meta.xml
<CustomObject>
    <label>Outbound Referral</label>
    <nameField>
        <displayFormat>OR-{00000000}</displayFormat>
        <label>Outbound Referral Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOps/force-app/main/default/objects/Outbound_Referral__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Outbound Referrals</relationshipLabel>
    <relationshipName>Outbound_Referrals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DevOps/force-app/main/default/objects/Outbound_Referral__c/fields/Outbound_Referral__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Referral__c</fullName>
    <description>FCS - Is this the Primary, Secondary, Tertiary or Other Referral?
(Must only have one of each)</description>
    <inlineHelpText>FCS - Is this the Primary, Secondary, Tertiary or Other Referral?
(Must only have one of each)</inlineHelpText>
    <label>Referral Profile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Tertiary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevOps/force-app/main/default/objects/Program__c/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <defaultValue>&quot;5 Day&quot;</defaultValue>
    <description>Business Hours field used to determine which business hours the Program uses for Case Note Locking</description>
    <inlineHelpText>Business Hours field used to determine which business hours the Program uses for Case Note Locking</inlineHelpText>
    <label>Business Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5 Day</fullName>
                <default>true</default>
                <label>5 Day</label>
            </value>
            <value>
                <fullName>7 Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DevOps/force-app/main/default/objects/Session__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Sessions related to the Case&apos;s Program may be selected</errorMessage>
        <filterItems>
            <field>$Source.Program__c</field>
            <operation>equals</operation>
            <valueField>Case.Program__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/fields/CIMS_Cluster_Id__c.field-meta.xml
<CustomField>
    <fullName>CIMS_Cluster_Id__c</fullName>
    <label>CIMS Cluster Id</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/fields/CIMS_Note_Id__c.field-meta.xml
<CustomField>
    <fullName>CIMS_Note_Id__c</fullName>
    <label>CIMS Note Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/fields/CIMS_Unique_Check__c.field-meta.xml
<CustomField>
    <fullName>CIMS_Unique_Check__c</fullName>
    <externalId>true</externalId>
    <label>CIMS Unique Check</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/fields/Indirect_Hours__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Hours__c</fullName>
    <label>zzDeprecated Indirect Hours</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/fields/Indirect_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Minutes__c</fullName>
    <label>zzDeprecated Indirect Minutes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Declined</fullName>
                <color>#F58145</color>
                <label>Declined 🟠</label>
            </value>
            <value>
                <fullName>Planning</fullName>
                <color>#6A2875</color>
                <default>true</default>
                <label>Planning 🟣</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <color>#0F9ED5</color>
                <label>Scheduled 🔵</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <color>#8AC540</color>
                <label>Confirmed 🟢</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#008A10</color>
                <label>Completed ✅</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#000000</color>
                <label>Cancelled ⚫</label>
            </value>
            <value>
                <fullName>No-show</fullName>
                <color>#DA2128</color>
                <label>No-show ❌</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/fields/Travel_Hours__c.field-meta.xml
<CustomField>
    <fullName>Travel_Hours__c</fullName>
    <label>zzDeprecated Travel Hours</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevOps/force-app/main/default/objects/Session__c/fields/Travel_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Travel_Minutes__c</fullName>
    <label>zzDeprecated Travel Minutes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DevOps/force-app/main/default/classes/sfCaseNoteTriggerHandler.cls
public class sfCaseNoteTriggerHandler extends TriggerHandler
{
    private static Map<Id, Case_Note__c> oldMap { get { return (Map<Id, Case_Note__c>) Trigger.oldMap;} }
    private static Map<Id, Case_Note__c> newMap { get { return (Map<Id, Case_Note__c>) Trigger.newMap;} }
    private static List<Case_Note__c> oldList { get { return (List<Case_Note__c>) Trigger.old;} }
    private static List<Case_Note__c> newList { get { return (List<Case_Note__c>) Trigger.new;} }

    public static List<Case_Note_Audit_Log__c> auditLogsToInsert = new List<Case_Note_Audit_Log__c>();
    public static Set<Id> sessionIdsToUpdateTimes = new Set<Id>();

    public override void beforeInsert()
    {
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault = true];
        BusinessHours bh2 = [SELECT Id FROM BusinessHours WHERE Name = 'Weekend Business Hours'];
        for(Case_Note__c n : newList)
        {
            n = setFields(n);
            
            if(n.Case__r.Program__r.Business_Hours__c == '7 Day'){
                n = setAutoLock(n, bh2);
            } else {
                n = setAutoLock(n, bh);
            }
            //must be last thing before end of before insert/update
            n = checkLockCaseNote(n);
        } 
    }
    
    public override void afterInsert()
    {
        for(Case_Note__c n : newList)
        {
            generateAuditLogEntry(n);
            if (n.session__c != null) { sessionIdsToUpdateTimes.add(n.Session__c); }
        }        
    }
    
    public override void beforeUpdate()
    {
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault = true];
        BusinessHours bh2 = [SELECT Id FROM BusinessHours WHERE Name = 'Weekend Business Hours'];
        for(Case_Note__c n : newList)
        {
            n = setFields(n);
            
            if(n.Case__r.Program__r.Business_Hours__c == '7 Day'){
                n = setAutoLock(n, bh2);
            } else {
                n = setAutoLock(n, bh);
            }
            //must be last thing before end of before insert/update
            n = checkLockCaseNote(n);
        } 
    }

    public override void afterUpdate()
    {
        for(Case_Note__c n : newList)
        {
            generateAuditLogEntry(n);
            if (n.session__c != null && (n.Indirect_Time_Hours__c != oldmap.get(n.Id).Indirect_Time_Hours__c || n.Travel_Time_Hours__c != oldmap.get(n.Id).Travel_Time_Hours__c)) { sessionIdsToUpdateTimes.add(n.Session__c); }
            if (oldmap.get(n.Id).Session__c != null && oldmap.get(n.Id).Session__c != n.Session__c) { sessionIdsToUpdateTimes.add(oldmap.get(n.Id).Session__c); }
            if (n.session__c != null && oldmap.get(n.Id).Session__c == null) { sessionIdsToUpdateTimes.add(n.Session__c); }
        }
    }
    
    public override void afterDelete()
    {
        for(Case_Note__c n : oldList)
        {
            if (n.session__c != null) { sessionIdsToUpdateTimes.add(n.Session__c); }
        }
    }

    //######## Private Methods #########
    
    @testVisible
    private static Case_Note__c setFields(Case_Note__c cn)
    {
        //CIMS unique Check
        cn.CIMS_Unique_Check__c = null;
        if(cn.CIMS_Cluster_Id__c != null && cn.CIMS_Note_Id__c != null){cn.CIMS_Unique_Check__c = cn.CIMS_Cluster_Id__c + '_' + cn.CIMS_Note_Id__c;}   
        
        return cn;
    }
    
    @TestVisible
    private static void generateAuditLogEntry(Case_Note__c n)
    {
        Case_Note_Audit_Log__c l = new Case_Note_Audit_Log__c();
        
        l.Case_Note__c = n.Id;
        l.Auto_Lock_Date_Time__c = n.Auto_Lock_Date_Time__c;
        l.Hours_Spent_With_Client__c = n.Hours_Spent_With_Client__c;
        l.Indirect_Hours__c = n.Indirect_Hours__c;
        l.Indirect_Minutes__c = n.Indirect_Minutes__c;
        l.Minutes_Spent_With_Client__c = n.Minutes_Spent_With_Client__c;
        l.Notes__c = n.Notes__c;
        l.Outbound_Referral__c = n.Outbound_Referral__c;
        l.Session__c = n.Session__c;
        l.Session_Participant__c = n.Session_Participant__c;
        l.Status__c = n.Status__c;
        l.Travel_Hours__c = n.Travel_Hours__c;
        l.Travel_Minutes__c= n.Travel_Minutes__c;
        
        auditLogsToInsert.add(l);
    }
    

    @TestVisible
    private static Case_Note__c setAutoLock(Case_Note__c n, BusinessHours bh)
    {
        DateTime lockFromDateTime = System.now();
        if(n.CreatedDate != null){lockFromDateTime = n.CreatedDate;}
    
        if(n.Auto_Lock_Date_Time__c == null && n.Status__c == 'Lock 8 Hours After Creation'){n.Auto_Lock_Date_Time__c = BusinessHours.add(bh.Id, System.now(), (8 * 60 * 60 * 1000));}
        
        if(n.Auto_Lock_Date_Time__c == null && n.Status__c == 'Lock 16 Hours After Creation'){n.Auto_Lock_Date_Time__c = BusinessHours.add(bh.Id, System.now(), (16 * 60 * 60 * 1000));}
                
        return n;
    }
    
    
    @TestVisible
    private static Case_Note__c checkLockCaseNote(Case_Note__c n)
    {
        if(n.Status__c == 'Lock Now'){n.Status__c = 'Locked';}        
        
        return n;
    }
    
    //######## Finally #########
    public override void andFinally()
    {//do stuff after everything else..

        if(auditLogsToInsert.size() > 0){insert auditLogsToInsert; auditLogsToInsert = new List<Case_Note_Audit_Log__c>();}
        if(sessionIdsToUpdateTimes.size() > 0) { sfHelpers.caseNoteTimeRollup(sessionIdsToUpdateTimes); sessionIdsToUpdateTimes.clear(); }
        
    }
}